### ISSUE TITLE
user_name isn't value

### ISSUE THREAD

**Issue by robosung** [cloudposse/terraform-aws-ses#10]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
`user_name` output but the script doesn't work as smtp username.  Using `access_key_id` works.

## Steps to Reproduce
1. Create ses instance using the terraform script
2. Try to send email using `user_name` and `ses_smtp_password` 
3. Auth error is return:
```SMTPAuthenticationError: (535, b'Authentication Credentials Invalid')```

## Environment (please complete the following information):
Module version `0.4.0`

**Comment by 3h4x** [comment]
Hey, 
The confusion comes from difference between what SES and IAM consider as username. I tried to explain that in `description` field with "The SMTP user which is access key ID." but I understand it could be more clear.
> Although your Amazon SES SMTP credentials are different than your AWS access keys and IAM user access keys, Amazon SES SMTP credentials are actually a type of IAM credentials. 
 
[Documentation](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-credentials.html) states three types of access:
- For SDK you should use access keys like in this example:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/examples-send-raw-using-sdk.html
- For SES SMTP endpoint you need - username (`access_key_id`) + password (`ses_smtp_password `). Where password is AWS secret key converted to SES SMTP password (SigV2 conversion algorithm) like in [docs](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html#smtp-credentials-convert) (we do that already and expose correct output)
- Console access

I will update README accordingly and I think we should have two examples, one for using SMTP with correct outputs and second for using API with correct outputs.

**Comment by robosung** [comment]
Thanks for the clarification.
