### ISSUE TITLE
Enable less restrictive policy

### ISSUE THREAD

**Issue by JohnLBevan** [cloudposse/terraform-aws-ses#19]
Currently the policy created for the IAM user account restricts the IAM user to mailing the related domain by setting `Resource` to `arn:aws:ses:<region>:<account+id>:identity/<domain>`.

The domain is passed in to say the sender's domain / it would be good if the created policy were less restrictive and allowed you to send to any domain (`"Resource": "*"`); or at least to have an option to specify this.

AWS allows this so long as you're out of their sandbox, or have verified the recipient's address, so it would be helpful if this module also allowed this.

**Comment by digigarlab** [comment]
I addressed this by creating another policy that I attached to the generated user:

```hcl
module "ses" {
  source      = "cloudposse/ses/aws"
  version     = "0.14.0"
  namespace   = var.namespace
  environment = var.environment

  domain        = var.domain
  zone_id       = var.zone_id
  verify_dkim   = true
  verify_domain = true
}

resource "aws_iam_policy" "ses" {
  name   = module.ses.user_name
  policy = data.aws_iam_policy_document.ses.json
}

resource "aws_iam_user_policy_attachment" "ses" {
  user       = module.ses.user_name
  policy_arn = aws_iam_policy.ses.arn
}

data "aws_iam_policy_document" "ses" {
  statement {
    # Replace with whatever you need
    resources = ["*"]
    actions   = ["ses:SendEmail", "ses:SendRawEmail"]
  }
}
```

**Comment by Gowiem** [comment]
@JohnLBevan See response here in #20: https://github.com/cloudposse/terraform-aws-ses/pull/20#issuecomment-821224642
