### ISSUE TITLE
Default permission limit sending email only to verified domain

### ISSUE THREAD

**Issue by ArchiFleKs** [cloudposse/terraform-aws-ses#40]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
I believe this line     
```
resources = [join("", aws_ses_domain_identity.ses_domain.*.arn)] 
```
prevent from sending email to outside domain.

When testing default credential I get a  ` Access denied: User `arn:aws:iam::920189201894:user/test' is not authorized to perform `ses:SendRawEmail' on resource `arn:aws:ses:eu-west-1:920189201894:identity/kevin@particule.io'` for exemple

My verified domain is another domain.

**Comment by CodechCFA** [comment]
Experiencing the same issue. Since there is no way to override that value, I cannot use this module.

**Comment by danjbh** [comment]
Alrighty, we should be good to go folks 👍
